# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1001, 703)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("background-color: grey;")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.num_6_btn = QtWidgets.QPushButton(self.widget_6)
        self.num_6_btn.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.num_6_btn.setFont(font)
        self.num_6_btn.setStyleSheet("QPushButton#num_6_btn {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#num_6_btn:hover{\n"
"    background-color: blue;\n"
"}\n"
"QPushButton#num_6_btn:pressed{\n"
"    background-color: red;\n"
"}")
        self.num_6_btn.setObjectName("num_6_btn")
        self.gridLayout_5.addWidget(self.num_6_btn, 0, 1, 1, 1)
        self.num_8_btn = QtWidgets.QPushButton(self.widget_6)
        self.num_8_btn.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.num_8_btn.setFont(font)
        self.num_8_btn.setStyleSheet("QPushButton#num_8_btn {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#num_8_btn:hover{\n"
"    background-color: blue;\n"
"}\n"
"QPushButton#num_8_btn:pressed{\n"
"    background-color: red;\n"
"}")
        self.num_8_btn.setObjectName("num_8_btn")
        self.gridLayout_5.addWidget(self.num_8_btn, 2, 1, 1, 1)
        self.num_7_btn = QtWidgets.QPushButton(self.widget_6)
        self.num_7_btn.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.num_7_btn.setFont(font)
        self.num_7_btn.setStyleSheet("QPushButton#num_7_btn {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#num_7_btn:hover{\n"
"    background-color: blue;\n"
"}\n"
"QPushButton#num_7_btn:pressed{\n"
"    background-color: red;\n"
"}")
        self.num_7_btn.setObjectName("num_7_btn")
        self.gridLayout_5.addWidget(self.num_7_btn, 1, 1, 1, 1)
        self.op_mult_btn = QtWidgets.QPushButton(self.widget_6)
        self.op_mult_btn.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.op_mult_btn.setFont(font)
        self.op_mult_btn.setStyleSheet("QPushButton#op_mult_btn {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#op_mult_btn:hover{\n"
"    background-color: blue;\n"
"}\n"
"\n"
"QPushButton#op_mult_btn:pressed{\n"
"    background-color: red;\n"
"}")
        self.op_mult_btn.setObjectName("op_mult_btn")
        self.gridLayout_5.addWidget(self.op_mult_btn, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_6, 1, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.num_0_btn = QtWidgets.QPushButton(self.widget_3)
        self.num_0_btn.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.num_0_btn.setFont(font)
        self.num_0_btn.setStyleSheet("QPushButton#num_0_btn {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#num_0_btn:hover{\n"
"    background-color: blue;\n"
"}\n"
"QPushButton#num_0_btn:pressed{\n"
"    background-color: red;\n"
"}")
        self.num_0_btn.setObjectName("num_0_btn")
        self.gridLayout_4.addWidget(self.num_0_btn, 1, 0, 1, 1)
        self.num_1_btn = QtWidgets.QPushButton(self.widget_3)
        self.num_1_btn.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.num_1_btn.setFont(font)
        self.num_1_btn.setStyleSheet("QPushButton#num_1_btn {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#num_1_btn:hover{\n"
"    background-color: blue;\n"
"}\n"
"QPushButton#num_1_btn:pressed{\n"
"    background-color: red;\n"
"}")
        self.num_1_btn.setObjectName("num_1_btn")
        self.gridLayout_4.addWidget(self.num_1_btn, 1, 1, 1, 1)
        self.num_2_btn = QtWidgets.QPushButton(self.widget_3)
        self.num_2_btn.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.num_2_btn.setFont(font)
        self.num_2_btn.setStyleSheet("QPushButton#num_2_btn {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#num_2_btn:hover{\n"
"    background-color: blue;\n"
"}\n"
"QPushButton#num_2_btn:pressed{\n"
"    background-color: red;\n"
"}")
        self.num_2_btn.setObjectName("num_2_btn")
        self.gridLayout_4.addWidget(self.num_2_btn, 1, 2, 1, 1)
        self.op_plus_btn = QtWidgets.QPushButton(self.widget_3)
        self.op_plus_btn.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.op_plus_btn.setFont(font)
        self.op_plus_btn.setStyleSheet("QPushButton#op_plus_btn {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#op_plus_btn:hover{\n"
"    background-color: blue;\n"
"}\n"
"\n"
"QPushButton#op_plus_btn:pressed{\n"
"    background-color: red;\n"
"}")
        self.op_plus_btn.setObjectName("op_plus_btn")
        self.gridLayout_4.addWidget(self.op_plus_btn, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.widget_3, 0, 1, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.num_9_btn = QtWidgets.QPushButton(self.widget_5)
        self.num_9_btn.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.num_9_btn.setFont(font)
        self.num_9_btn.setStyleSheet("QPushButton#num_9_btn {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#num_9_btn:hover{\n"
"    background-color: blue;\n"
"}\n"
"QPushButton#num_9_btn:pressed{\n"
"    background-color: red;\n"
"}")
        self.num_9_btn.setObjectName("num_9_btn")
        self.gridLayout_6.addWidget(self.num_9_btn, 0, 0, 1, 1)
        self.op_c_btn = QtWidgets.QPushButton(self.widget_5)
        self.op_c_btn.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.op_c_btn.setFont(font)
        self.op_c_btn.setStyleSheet("QPushButton#op_c_btn {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#op_c_btn:hover{\n"
"    background-color: blue;\n"
"}\n"
"\n"
"QPushButton#op_c_btn:pressed{\n"
"    background-color: red;\n"
"}")
        self.op_c_btn.setObjectName("op_c_btn")
        self.gridLayout_6.addWidget(self.op_c_btn, 0, 3, 1, 1)
        self.op_e_btn = QtWidgets.QPushButton(self.widget_5)
        self.op_e_btn.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.op_e_btn.setFont(font)
        self.op_e_btn.setStyleSheet("QPushButton#op_e_btn {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#op_e_btn:hover{\n"
"    background-color: blue;\n"
"}\n"
"\n"
"QPushButton#op_e_btn:pressed{\n"
"    background-color: red;\n"
"}")
        self.op_e_btn.setObjectName("op_e_btn")
        self.gridLayout_6.addWidget(self.op_e_btn, 0, 2, 1, 1)
        self.op_divide_btn = QtWidgets.QPushButton(self.widget_5)
        self.op_divide_btn.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.op_divide_btn.setFont(font)
        self.op_divide_btn.setStyleSheet("QPushButton#op_divide_btn {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#op_divide_btn:hover{\n"
"    background-color: blue;\n"
"}\n"
"\n"
"QPushButton#op_divide_btn:pressed{\n"
"    background-color: red;\n"
"}")
        self.op_divide_btn.setObjectName("op_divide_btn")
        self.gridLayout_6.addWidget(self.op_divide_btn, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.widget_5, 2, 1, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.widget)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.num_4_btn = QtWidgets.QPushButton(self.widget_7)
        self.num_4_btn.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.num_4_btn.setFont(font)
        self.num_4_btn.setStyleSheet("QPushButton#num_4_btn {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#num_4_btn:hover{\n"
"    background-color: blue;\n"
"}\n"
"QPushButton#num_4_btn:pressed{\n"
"    background-color: red;\n"
"}")
        self.num_4_btn.setObjectName("num_4_btn")
        self.gridLayout_3.addWidget(self.num_4_btn, 1, 0, 1, 1)
        self.num_3_btn = QtWidgets.QPushButton(self.widget_7)
        self.num_3_btn.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.num_3_btn.setFont(font)
        self.num_3_btn.setStyleSheet("QPushButton#num_3_btn {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#num_3_btn:hover{\n"
"    background-color: blue;\n"
"}\n"
"QPushButton#num_3_btn:pressed{\n"
"    background-color: red;\n"
"}")
        self.num_3_btn.setObjectName("num_3_btn")
        self.gridLayout_3.addWidget(self.num_3_btn, 0, 0, 1, 1)
        self.num_5_btn = QtWidgets.QPushButton(self.widget_7)
        self.num_5_btn.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.num_5_btn.setFont(font)
        self.num_5_btn.setStyleSheet("QPushButton#num_5_btn {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#num_5_btn:hover{\n"
"    background-color: blue;\n"
"}\n"
"QPushButton#num_5_btn:pressed{\n"
"    background-color: red;\n"
"}")
        self.num_5_btn.setObjectName("num_5_btn")
        self.gridLayout_3.addWidget(self.num_5_btn, 2, 0, 1, 1)
        self.op_minus_btn = QtWidgets.QPushButton(self.widget_7)
        self.op_minus_btn.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.op_minus_btn.setFont(font)
        self.op_minus_btn.setStyleSheet("QPushButton#op_minus_btn {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#op_minus_btn:hover{\n"
"    background-color: blue;\n"
"}\n"
"\n"
"QPushButton#op_minus_btn:pressed{\n"
"    background-color: red;\n"
"}")
        self.op_minus_btn.setObjectName("op_minus_btn")
        self.gridLayout_3.addWidget(self.op_minus_btn, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.widget_7, 1, 2, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2.addWidget(self.widget_4, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.gridLayout.addWidget(self.widget_2, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 4)
        self.gridLayout.setRowStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.num_6_btn.setText(_translate("MainWindow", "6"))
        self.num_8_btn.setText(_translate("MainWindow", "8"))
        self.num_7_btn.setText(_translate("MainWindow", "7"))
        self.op_mult_btn.setText(_translate("MainWindow", "x"))
        self.num_0_btn.setText(_translate("MainWindow", "0"))
        self.num_1_btn.setText(_translate("MainWindow", "1"))
        self.num_2_btn.setText(_translate("MainWindow", "2"))
        self.op_plus_btn.setText(_translate("MainWindow", "+"))
        self.num_9_btn.setText(_translate("MainWindow", "9"))
        self.op_c_btn.setText(_translate("MainWindow", "C"))
        self.op_e_btn.setText(_translate("MainWindow", "E"))
        self.op_divide_btn.setText(_translate("MainWindow", "/"))
        self.num_4_btn.setText(_translate("MainWindow", "4"))
        self.num_3_btn.setText(_translate("MainWindow", "3"))
        self.num_5_btn.setText(_translate("MainWindow", "5"))
        self.op_minus_btn.setText(_translate("MainWindow", "-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
